version: "3"
services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - pg_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend_pokemon
    environment:
      DB_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      GMAIL_USER: ${GMAIL_USER}
      GMAIL_PASSWORD: ${GMAIL_PASSWORD}
      FROM: ${FROM}
      JWT_SECRET: ${JWT_SECRET}
      DB_SSL: false
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - pg_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend_pokemon
    ports:
      - "4000:4000"
    depends_on:
      - backend

volumes:
  postgres-data:

networks:
  pg_network:
    driver: bridge
